openapi: 3.0.1
info:
  title: Test Copilot For SportMonks
  description: This API is dedicated for sports enthusiasts. Retrieve all sports-related data using this API. Sportmonks offers standard REST APIs. Requests are sent with URLs, and responses will be returned in JSON format. Every authentication is handled by an API token.
  version: 0.1.0
servers:
  - url: https://dummyjson.com
paths:
  /products/1:
    get:
      operationId: getProduct
      summary: Get football fixtures
      description: Retrieve information about football fixtures.
      responses:
        "200":
          description: Successful response
